- api/routers/authRouter.js
- example_model.md
- firebase/auth/authHelpers.js
- firebase/config/firebase.js
Configure server for Firebase Admin access (the right way to do it)
Add revised register method to work with register endpoint.  Still needs DB support added back in.
> Fix Firebase Config / Revise Register endpoint

- firebase/auth/authHelpers.js
Removed .toJSON() because I forgot to earlier
> Fix mistake

- api/routers/authRouter.js
- database/users/usersHelper.js
Created an add user to create a new document in the 'users' collection in the DB.
- Document title is unique user id generated by Firebase
- So far, email address and hashed password are added.  
- Will probably refine later to add more relavant information.
> Create DB support for register endpoint

- api/routers/authRouter.js
- database/users/usersHelper.js
Did a quick refactor of register endpoint and add user DB helper.  Should be easier to revise now with more information.
> Pretty up the helper and endpoint.

- api/routers/authRouter.js
- database/users/usersHelper.js
- get user document by uid (unique identifier string across all authentication methods)
- get user document by email
> Add get user helper methods

- database/users/usersHelper.js
Delete and edit/update user records helper methods created
> Finish Users DB helper methods

- api/routers/userRouter.js
Adds endpoint to get a user by ID. Pulled from master
> Adds get by ID for users

- api/routers/userRouter.js
- api/server.js
- yarn.lock
Works fine on another students machine except for mine
> Debugging GET by ID

- package.json
- yarn.lock
Removed general firebase package to see if there was a conflict happening on the deployed server
> Update package list

- api/routers/userRouter.js
Implants listAllUsers firebase method, seems to only work in the console as of now.
> Implants listAllUsers

- api/routers/userRouter.js
GET all users & GET by ID work, for now, we have to grab the ID from the firebase console until it's sorted out.
> GET all Users & GET user by ID implanted and working fine

- api/routers/userRouter.js
- api/server.js
```
{
"uid": "example uid",
"email": "my_email@email.com
}
```
> GET all users endpoint now responds with an array of all users

- api/routers/userRouter.js
- index.js
Delete method implanted, endpoint in progress.
> delete method implanted

- api/routers/userRouter.js
DELETE method and endpoint completed, not fully functional at the moment. Doesn't delete from database but says it works
> DELETE method and endpoint completed, not fully functional at the moment

- api/routers/tripRouter.js
- api/server.js
- database/trips/tripsHelper.js
- firebase/auth/authMiddleware.js
- yarn.lock
- GET by id
- PUT by id (edit trip)
- DELETE by id
- deletes trips
- need to work on response
> Trip endpoints

- api/routers/userRouter.js
DELETE endpoint complete as of now. Postman says it works, Jonathan said delete is having issues right now. So I'll start working on Update
> DELETE endpoint complete, starting update now

- api/routers/userRouter.js
- database/users/usersHelper.js
- index.js
> Get trips by user id endpoint

- api/routers/tripRouter.js
- api/routers/userRouter.js
Pulled master
Add endpoint for adding new trip
- requires `name`, `destination`, `planner` (user id)
- can also take `startDate`, `endDate`
- can add other info down the line
> Add POST trip endpoint

- api/routers/tripRouter.js
- database/destinations/destinationHelper.js
- get by id helper
- add destination helper
Not much need for modify or delete helpers, as these will be mainly used as references, so they should be reused as needed.
> Add destination DB helpers

- api/routers/userRouter.js
Update user method for firebase added.
> Added Update user method

- api/routers/userRouter.js
> Debugging PUT Endpoint

- api/routers/tripRouter.js
- database/destinations/destinationHelper.js
- database/trips/tripsHelper.js
- database/users/usersHelper.js
- yarn.lock
New endpoint to set destination in trip
Fix get trip by id endpoint to NOT respond with sensitive information
> Destination set in trip document

- api/routers/userRouter.js
Use /users/all in postman to get a list of the first 5 users
>  Changed GET all users endpoint to users/all

- api/routers/favoritesRouter.js
- api/routers/userRouter.js
- api/server.js
- database/favorites/faveHelpers.js
Added some favorites DB helpers and endpoints, more to come...
> Almost there

- api/routers/userRouter.js
User endpoints have been completed and tested, all seem to work fine on my end.
> All User endpoints complete and tested.

- api/routers/favoritesRouter.js
- database/favorites/faveHelpers.js
- database/index.js
- database/users/usersHelper.js
PUT `/:userId` :  body requires field `favId`, value is id of "favorite" document
DELETE `/:userId` : same as above
> Add some endpoints for favorites

- api/routers/tripRouter.js
- database/destinations/destinationHelper.js
The add trip endpoint is now more in line with the final data model
> Add trip endpoint functionality

- api/routers/userRouter.js
- api/server.js
- database/index.js
- database/users/faker.js
- package.json
- yarn.lock
Figured out fakerjs a bit. Works for generating(not actually adding yet) one user as of now will continue implementing it.
> Starts adding fakerjs, works for generating(not adding yet)

- database/users/faker.js
`console.log(a)` removed in faker.js file so it doesn't generate 500 users each time the server boots up. Also added a comment on how to generate a new list of users to line 11.
> Removed console.log in faker.js

- api/routers/tripRouter.js
- database/users/faker.js
- firebase/auth/authMiddleware.js
- yarn.lock
gRPC was acting up, this fixed it last time
> Hopefully this will fix our registering problem

- api/routers/favoritesRouter.js
- api/routers/tripRouter.js
- database/favorites/faveHelpers.js
- yarn.lock
Add favorites to trip endpoint no longer accepts empty objects
> Fix favorites

- api/routers/tripRouter.js
- database/trips/tripsHelper.js
Simplified some of the back-end to better work with the front-end.
Feature-creep like whoa on my part a few weeks back
> Some revisions to work better with front-end

- api/routers/tripRouter.js
- api/routers/userRouter.js
- api/server.js
- database/users/usersHelper.js
- firebase/auth/authMiddleware.js
- yarn.lock
Fix get trips by user endpoint to include trip id's
> Minor changes to facilitate front-end

- api/payments/paymentRouter.js
- api/server.js
Stripe code seems to be breaking backend server. Will finish frontend and investigate after
> Commented out stripe code for now

- yarn.lock
Again with the security notifications!
> Security upgrade

- api/stripe/paymentRouter.js
Removed console.log() in paymentRouter
> console.log cleanup 

- api/routers/tripRouter.js
- database/lists/listHelpers.js
Revamped endpoints and DB helpers for trip checklists system
> Overhaul to list helpers and endpoints
